//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public int id { get; set; }
        public Nullable<int> employeeId { get; set; }
        public string name { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
